### ISSUE TITLE
TODO: Rozdzielenie formularzy na osobne pliki

### ISSUE THREAD

**Issue by TomaszJ1** [dzikus13/league#15]
Obecnie na stronie, wszystkie formularze znajdują się w jednym pliku. Jeśli dobrze pamiętam ktoś wspomniał o, tak jak w temacie, rozdzieleniu formularzy. (Zadanie, nie zrealizowane, w poniedziałek.)

**Comment by rs-piotr-kryska** [comment]
Please: Be more specific. Use English. Not as a strict requirement - just to get used to use English at work. Even bad English.

**Comment by IgaBroton** [comment]
please finally do a pull request

**Comment by TomaszJ1** [comment]
The newest pull request contains the split.
